# Automatically generated by configure - do not modify
TARGET_ARM=y
TARGET_NAME=arm
TARGET_BASE_ARCH=arm
TARGET_ABI_DIR=arm
CONFIG_SOFTMMU=y
TARGET_XML_FILES= /emulador-stm32-Bluepill/docker/qemu/qemu_stm32/gdb-xml/arm-core.xml /emulador-stm32-Bluepill/docker/qemu/qemu_stm32/gdb-xml/arm-vfp.xml /emulador-stm32-Bluepill/docker/qemu/qemu_stm32/gdb-xml/arm-vfp3.xml /emulador-stm32-Bluepill/docker/qemu/qemu_stm32/gdb-xml/arm-neon.xml
CONFIG_I386_DIS=y
CONFIG_ARM_DIS=y
LDFLAGS+=
QEMU_CFLAGS+=
